name: planet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.3+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/5.jpeg
    - assets/whats.jpg
    - assets/signin.png
    - assets/01.png
    - assets/Asset1.png
    - assets/plant5.png
    - assets/plant-four.png
    - assets/thank2.png
    
